name = "OptimizingIR"
uuid = "cc8fcbce-1519-41ac-a9d5-7b019a31028d"
authors = ["Felipe Noronha <felipenoris@gmail.com>"]
version = "0.0.1"

[compat]
BenchmarkTools = "0.4"
julia = "1"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BenchmarkTools"]
